name: Lets Start MissHannaRobot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "This command only works in Groups"
          replace: "à´ˆ à´•à´®à´¾àµ»à´¡àµ à´—àµà´°àµ‚à´ªàµà´ªà´¿àµ½ à´®à´¾à´¤àµà´°à´®àµ‡ à´µàµ¼à´•àµà´•àµâ€Œ à´†à´µàµà´•à´¯àµà´³àµà´³àµ.."
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Welcome to HannahğŸ”¥ nice to meet you ğŸ˜ğŸ€'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Mr-Dark-Prince
          commit_user_email: 73339924+Mr-Dark-Prince@users.noreply.github.com
          commit_author: Mr-Dark-Prince <73339924+Mr-Dark-Prince@users.noreply.github.com>
